In [1]:
import urllib
from bs4 import BeautifulSoup

In [2]:
url = 'https://www.yanolja.com/pension/r-900252?advert=AREA&topAdvertiseMore=0'
#html_str이라는 변수에 저장된 내용은 위의 url에 해당하는 전체 웹페이지가 하나의 문자열
with urllib.request.urlopen(url) as html_str:
    soup= BeautifulSoup(html_str, 'lxml')
soup

<!DOCTYPE html>
<html><head><link href="//yaimg.yanolja.com" rel="dns-prefetch"/><link href="https://yaimg.yanolja.com" rel="preconnect"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_16x16.png" rel="shortcut icon"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_16x16.png" rel="icon"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_16x16.png" rel="icon" sizes="16x16"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_32x32.png" rel="icon" sizes="32x32"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_57x57.png" rel="icon" sizes="57x57"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_72x72.png" rel="icon" sizes="72x72"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_96x96.png" rel="icon" sizes="96x96"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_120x120.png" rel="icon" sizes="120x120"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_128x128.png" rel="icon" sizes="128x128"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_144x144.png" rel="icon" sizes="144x144"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_152x152.png" rel="icon" sizes="152x152"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_195x195.png" rel="icon" sizes="195x195"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_228x228.png" rel="icon" sizes="228x228"/><script src="https://polyfill.io/v3/polyfill.min.js?features=Math.sign%2CMath.trunc%2CIntersectionObserver%2CIntersectionObserverEntry" type="text/javascript"></script><script type="text/javascript">function __gmi(){window.ya__.onGoogleMapLoaded()};window.ya__={"gaID":"UA-87400434-10","googleMapAPIKey":"AIzaSyDJbfSpMwCTyXVW-22Hxj-R6-pELc5-fkM","identityPoolID":"ap-northeast-2:f1b4fd4d-e1c2-4b17-ae55-a738dd0c7ae9","isLoggedIn":false,"kakaoAPIKey":"3cf7cfbaf7ad7394f7d53b01eea4bdd6","runMode":"production","streamName":"live-ya-webclient-log","version":"4.12.2"}</script><script src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=gbtjg2bddr" type="text/javascript"></script><script type="application/ld+json">{"@context":"http://schema.org","@type":"Organization","url":"https://www.yanolja.com/","logo":"https://yaimg.yanolja.com/public/icon/yanolja.svg"}</script><script type="application/ld+json">{"@context":"http://schema.org","@type":"Person","name":"야놀자 : 초특가 숙박 예약","url":"https://www.yanolja.com/","sameAs":["https://www.facebook.com/yanolja/","https://www.instagram.com/yanolja.official/","https://www.youtube.com/user/yanoljamedia","http://tv.naver.com/yanolja","http://post.naver.com/my.nhn?memberNo=2768780","http://blog.naver.com/yanolog","https://play.google.com/store/apps/details?id=com.cultsotry.yanolja.nativeapp","https://itunes.apple.com/kr/app/%EC%95%BC%EB%86%80%EC%9E%90/id436731843?mt=8","https://yanolja.github.io/","https://start.yanolja.com"]}</script><script type="text/javascript">(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-58KLNBW');</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=AW-1002996711"></script><script type="text/javascript">window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'AW-1002996711'); </script><script type="text/javascript">
                !function(f,b,e,v,n,t,s)
                {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                n.callMethod.apply(n,arguments):n.queue.push(arguments)};
                if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
                n.queue=[];t=b.createElement(e);t.async=!0;
                t.src=v;s=b.getElementsByTagName(e)[0];
                s.parentNode.insertBefore(t,s)}(window, document,'script',
                'https://connect.facebook.net/en_US/fbevents.js');
                fbq('init', '408076496057547');
                fbq('track', 'PageView');

In [3]:
name=soup.find("strong","PlaceListTitle_text__2511B.normal")
name

In [4]:
pip install selenium

Requirement already satisfied: selenium in ./opt/anaconda3/lib/python3.9/site-packages (4.5.0)
Requirement already satisfied: trio~=0.17 in ./opt/anaconda3/lib/python3.9/site-packages (from selenium) (0.22.0)
Requirement already satisfied: trio-websocket~=0.9 in ./opt/anaconda3/lib/python3.9/site-packages (from selenium) (0.9.2)
Requirement already satisfied: urllib3[socks]~=1.26 in ./opt/anaconda3/lib/python3.9/site-packages (from selenium) (1.26.9)
Requirement already satisfied: certifi>=2021.10.8 in ./opt/anaconda3/lib/python3.9/site-packages (from selenium) (2021.10.8)
Requirement already satisfied: sniffio in ./opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: async-generator>=1.9 in ./opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in ./opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (1.0.0)
Requirement already satisfied: sortedcontainers in ./opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in ./opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: outcome in ./opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: attrs>=19.2.0 in ./opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: wsproto>=0.14 in ./opt/anaconda3/lib/python3.9/site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in ./opt/anaconda3/lib/python3.9/site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in ./opt/anaconda3/lib/python3.9/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
from selenium import webdriver #웹서버에 데이터를 요청하는 라이브러리 
import time
from tqdm import tqdm_notebook
import pandas as pd

In [6]:
driver=webdriver.Chrome('/Users/kimminkyoung/Desktop/driver/chromedriver')

/var/folders/h2/vg8hq2t90w95gjs4qhmc91qw0000gn/T/ipykernel_2915/2196827861.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome('/Users/kimminkyoung/Desktop/driver/chromedriver')

In [7]:
driver.get(url)

In [100]:
html=driver.page_source
soup=driver.page_source
soup=BeautifulSoup(html,'lxml')
soup

<html><head><link href="//yaimg.yanolja.com" rel="dns-prefetch"/><link href="https://yaimg.yanolja.com" rel="preconnect"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_16x16.png" rel="shortcut icon"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_16x16.png" rel="icon"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_16x16.png" rel="icon" sizes="16x16"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_32x32.png" rel="icon" sizes="32x32"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_57x57.png" rel="icon" sizes="57x57"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_72x72.png" rel="icon" sizes="72x72"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_96x96.png" rel="icon" sizes="96x96"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_120x120.png" rel="icon" sizes="120x120"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_128x128.png" rel="icon" sizes="128x128"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_144x144.png" rel="icon" sizes="144x144"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_152x152.png" rel="icon" sizes="152x152"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_195x195.png" rel="icon" sizes="195x195"/><link href="//yaimg.yanolja.com/joy/sunny/static/images/favicon/favicon_228x228.png" rel="icon" sizes="228x228"/><script async="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="https://polyfill.io/v3/polyfill.min.js?features=Math.sign%2CMath.trunc%2CIntersectionObserver%2CIntersectionObserverEntry" type="text/javascript"></script><script defer="" src="//yaimg.yanolja.com/joy/sunny/static/images/kakao.min.js" type="text/javascript"></script><script type="application/ld+json">{"@context":"http://schema.org","@type":"Organization","url":"https://www.yanolja.com/","logo":"https://yaimg.yanolja.com/public/icon/yanolja.svg"}</script><script type="application/ld+json">{"@context":"http://schema.org","@type":"Person","name":"야놀자 : 초특가 숙박 예약","url":"https://www.yanolja.com/","sameAs":["https://www.facebook.com/yanolja/","https://www.instagram.com/yanolja.official/","https://www.youtube.com/user/yanoljamedia","http://tv.naver.com/yanolja","http://post.naver.com/my.nhn?memberNo=2768780","http://blog.naver.com/yanolog","https://play.google.com/store/apps/details?id=com.cultsotry.yanolja.nativeapp","https://itunes.apple.com/kr/app/%EC%95%BC%EB%86%80%EC%9E%90/id436731843?mt=8","https://yanolja.github.io/","https://start.yanolja.com"]}</script><meta charset="utf-8"/><meta content="initial-scale=1, maximum-scale=1, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover" name="viewport"/><title>포항 스타스케이프풀빌라 사진, 가격, 위치소개 | 야놀자</title><meta content="펜션, 풀빌라도 야놀자에서 초특가검색, 바로예약! 포항 스타스케이프풀빌라 경상북도 포항시 남구 호미곶면 구만길 224 " name="description"/><meta content="포항 스타스케이프풀빌라 할인, 포항 스타스케이프풀빌라 예약, 포항 스타스케이프풀빌라 가격, 포항 스타스케이프풀빌라 위치, 야놀자, 펜션예약" name="keywords"/><meta content="포항 스타스케이프풀빌라 사진, 가격, 위치소개 | 야놀자" property="og:title"/><meta content="펜션, 풀빌라도 야놀자에서 초특가검색, 바로예약! 포항 스타스케이프풀빌라 경상북도 포항시 남구 호미곶면 구만길 224 " property="og:description"/><meta content="https://yaimg.yanolja.com/v5/2022/09/20/12/6329b4523f1207.98999308.jpg" property="og:image"/><meta content="website" property="og:type"/><meta content="summary" name="twitter:card"/><meta content="포항 스타스케이프풀빌라 사진, 가격, 위치소개 | 야놀자" name="twitter:title"/><meta content="펜션, 풀빌라도 야놀자에서 초특가검색, 바로예약! 포항 스타스케이프풀빌라 경상북도 포항시 남구 호미곶면 구만길 224 " name="twitter:description"/><link href="https://place-site.yanolja.com/places/10041396" rel="canonical"/><script type="application/ld+json">{"@context":"http://schema.org","@type":"Resort","name":"포항 스타스케이프풀빌라","description":"아름다운 일출이 있는 포항 바다와 럭셔리한 프라이빗 인피니티풀을 경험할 수 있는 명품 풀빌라 스타스케이프입니다.","image":"https://yaimg.yanolja.com/v5/2022/09/20/12/6329b4523f1207.98999308.jpg","telephone":"050350590348","address":{"@type":"PostalAddress","addressLocality":"경상북도 포항시 남구 호미곶면 구만길 224 "},"aggregateRating":{"@type":"AggregateRating","worstRating":1,"bestRating":5,"ratingValue":4.8276,"reviewCount":58},"priceRange":"숙박 : 177,500원 ~ 800,000원","geo":{"@type":"GeoCoordinates","latitude":36.0849592730963,"longitude":129.556678751497},"amenityFeature":[{"@type":"LocationFeatureSpecification","name":"프리미엄\n펜션","value":"True"},{"@type":"LocationFeatureSpecification","name":"주차가능","value":"True"},{"@type":"LocationFeatureSpecification","name":"야외수영장","value":"True"},{"@type":"LocationFeatureSpecification","name":"조식운영\n(뷔페)","value":"True"},{"@type":"LocationFeatureSpecification","name":"풀빌라","value":"True"},{"@type":"LocationFeatureSpecification","name":"복층구조","value":"True"},{"@type":"LocationFeatureSpecification","name":"매점/\n편의점","value":"True"},{"@type":"LocationFeatureSpecification","name":"커피숍","value":"True"},{"@type":"LocationFeatureSpecification","name":"투어","value":"True"}],"petsAllowed":"","keywords":"포항 스타스케이프풀빌라 할인, 포항 스타스케이프풀빌라 예약, 포항 스타스케이프풀빌라 가격, 포항 스타스케이프풀빌라 위치, 야놀자, 펜션예약"}</script><link as="image" href="https://yaimg.yanolja.com/v5/2022/09/20/12/640/6329b4523f1207.98999308.jpg" rel="preload"/><meta content="15" name="next-head-count"/><link as="style" crossorigin="anonymous" href="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/css/36ebbd827594f556.css" rel="preload"/><link crossorigin="anonymous" data-n-g="" href="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/css/36ebbd827594f556.css" rel="stylesheet"/><link as="style" crossorigin="anonymous" href="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/css/dd19a6863df21303.css" rel="preload"/><link crossorigin="anonymous" data-n-p="" href="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/css/dd19a6863df21303.css" rel="stylesheet"/><noscript data-n-css=""></noscript><script crossorigin="anonymous" defer="" nomodule="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/polyfills-5cd94c89d3acac5f.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/709.8aea15081bc46a86.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/webpack-cba904c7c21c42eb.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/framework-fda7fa95de900d79.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/main-2926ac36ad8f5c5a.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/pages/_app-8ab29a0f8ce88001.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/0a301732-2244cf7c6f26abc2.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/ea88be26-0fef59026b1b3d49.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/1a93a35e-c7be4308764fe9f8.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/41-120f4836696d77b2.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/861-9d341a0ee18a7af7.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/209-88b2b08db5b4da8b.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/722-bd96fc6d4103760b.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/981-4bf034900e23892d.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/822-0f297d864f8558f1.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/921-f3afc4e96a44b214.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/968-ac40f3b9a7dba31c.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/chunks/pages/places/%5Bplace_no%5D-4c283ffd1663f21b.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/v7Ij9JheVM68-PuXqrlav/_buildManifest.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/v7Ij9JheVM68-PuXqrlav/_ssgManifest.js"></script><script crossorigin="anonymous" defer="" src="https://assets.yanolja.com/fbf460493090a17fa0c32461a55fc890a6a3b3fc/202211101359/_next/static/v7Ij9JheVM68-PuXqrlav/_middlewareManifest.js"></script><style data-emotion="css utbbsy" data-s="">.css-utbbsy{width:100vw;background:#f2f2f2;height:100%;}</style><style data-emotion="css fwupcd" data-s="">.css-fwupcd{max-width:768px;margin:0 auto;min-width:320px;z-index:0;padding-top:env(safe-area-inset-top);}</style><style data-emotion="css hqn261" data-s="">.css-hqn261{padding-top:48px;width:100%;min-height:100%;height:100%;overflow-x:hidden;background:#ffffff;position:relative;}</style><style data-emotion="css gs34ha" data-s="">.css-gs34ha{border-bottom:0.8rem solid #f2f2f2;}</style><style data-emotion="css 1wpv5ik" data-s="">.css-1wpv5ik{width:100%;cursor:pointer;position:relative;overflow:hidden;height:calc(min(66.7vw, 50.7rem));max-height:calc(min(66.7vw, 50.7rem));z-index:0;background-color:#f2f2f2;-webkit-transform:translateZ(0);-moz-transform:translateZ(0);-ms-transform:translateZ(0);transform:translateZ(0);will-change:transform;}@media screen and (min-width: 768px){.css-1wpv5ik{height:50.7rem;}.css-1wpv5ik .photoSwipeItem{height:50.7rem;}}</style><style data-emotion="css of933b" data-s="">.css-of933b{cursor:not-allowed;pointer-events:auto!important;top:50%;position:absolute;z-index:1;left:2rem;-webkit-transform:translateY(-50%);-moz-transform:translateY(-50%);-ms-transform:translateY(-50%);transform:translateY(-50%);width:4.6rem!important;height:7.4rem!important;}.css-of933b:before{content:'';width:100%;height:100%;display:inline-block;background-image:url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDYiIGhlaWdodD0iNzQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGcgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj48cmVjdCBmaWxsPSIjMDAwIiBvcGFjaXR5PSIuMyIgd2lkdGg9IjQ2IiBoZWlnaHQ9Ijc0IiByeD0iNCIvPjxwYXRoIGQ9Ik0zNSA2MmgtMi40TDggMzdsMjQuNi0yNUgzNUwxMC40IDM3eiIgZmlsbD0iI0ZGRiIgb3BhY2l0eT0iLjIiLz48L2c+PC9zdmc+');background-repeat:no-repeat;-webkit-background-position:right;background-position:right;-webkit-background-size:contain;background-size:contain;}</style><style data-emotion="css ur11hq" data-s="">.css-ur11hq{background:#f2f2f2;position:relative;width:100%;height:66.7vw;max-height:50.7rem;margin:0;display:inline-block;}</style><style data-emotion="css sr2c7j" data-s="">.css-sr2c7j{object-fit:cover;height:100%;}</style><style data-emotion="css 1xxykgc" data-s="">.css-1xxykgc{cursor:not-allowed;pointer-events:auto!important;top:50%;position:absolute;z-index:1;right:2rem;-webkit-transform:translateY(-50%);-moz-transform:translateY(-50%);-ms-transform:translateY(-50%);transform:translateY(-50%);width:4.6rem!important;height:7.4rem!important;}.css-1xxykgc:before{content:'';width:100%;height:100%;display:inline-block;background-image:url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDYiIGhlaWdodD0iNzQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGcgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj48cmVjdCBmaWxsPSIjMDAwIiBvcGFjaXR5PSIuMyIgd2lkdGg9IjQ2IiBoZWlnaHQ9Ijc0IiByeD0iNCIvPjxwYXRoIGQ9Ik0xMSA2MmgyLjRMMzggMzcgMTMuNCAxMkgxMWwyNC42IDI1eiIgZmlsbD0iI0ZGRiIgb3BhY2l0eT0iLjIiLz48L2c+PC9zdmc+');background-repeat:no-repeat;-webkit-background-position:right;background-position:right;-webkit-background-size:contain;background-size:contain;}</style><style data-emotion="css 3yjbuh" data-s="">.css-3yjbuh{width:100%;position:absolute;left:0;bottom:0;}</style><style data-emotion="css arr6gp" data-s="">.css-arr6gp{padding:1.6rem 0;}</style><style data-emotion="css 17wo4sw" data-s="">.css-17wo4sw{padding:0 2rem;cursor:default;}.css-17wo4sw >span{margin-bottom:0.4rem;}</style><style data-emotion="css 1huuymp" data-s="">.css-1huuymp{padding:0 2rem;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;}</style><style data-emotion="css jyf8pg" data-s="">.css-jyf8pg{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;margin-top:0.4rem;padding:0 2rem;}</style><style data-emotion="css fie5xt" data-s="">.css-fie5xt{-webkit-flex:1;-ms-flex:1;flex:1;font-size:2rem;font-weight:bold;max-width:calc(100% - 4.8rem);color:#1a1a1a;line-height:1.1;max-height:2.1em;text-align:left;position:relative;text-overflow:ellipsis;padding:0!important;word-break:break-word;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;}</style><style data-emotion="css 69d871" data-s="">.css-69d871{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-pack:justify;-webkit-justify-content:space-between;justify-content:space-between;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;margin-left:1.2rem;}.css-69d871 >div{margin:0;}.css-69d871 >div:before{margin-left:1.2rem;width:2rem;height:2rem;}</style><style data-emotion="css 1btrnfr" data-s="">.css-1btrnfr{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;margin:0.2rem;cursor:pointer;}.css-1btrnfr:before{display:inline-block;content:'';width:2rem;height:2rem;background-image:url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTEyIDEwLjA1Yy0uNTA3IDAtLjk2LjE4OC0xLjMwNy40ODFMNS45NCA3LjkzN0M1Ljk3MyA3Ljc5NSA2IDcuNjUgNiA3LjVjMC0uMTUtLjAyNy0uMjk0LS4wNi0uNDM4bDQuNy0yLjU2OEMxMSA0LjgwNiAxMS40NzMgNSAxMiA1YzEuMTA3IDAgMi0uODM4IDItMS44NzUgMC0xLjAzOC0uODkzLTEuODc1LTItMS44NzVzLTIgLjgzNy0yIDEuODc1YzAgLjE1LjAyNy4yOTQuMDYuNDM4TDUuMzYgNi4xM0EyLjA2NSAyLjA2NSAwIDAwNCA1LjYyNWMtMS4xMDcgMC0yIC44MzgtMiAxLjg3NXMuODkzIDEuODc1IDIgMS44NzVjLjUyNyAwIDEtLjE5NCAxLjM2LS41MDZsNC43NDcgMi42YTEuNjU5IDEuNjU5IDAgMDAtLjA1NC40MDZjMCAxLjAwNi44NzQgMS44MjUgMS45NDcgMS44MjVzMS45NDctLjgxOSAxLjk0Ny0xLjgyNVMxMy4wNzMgMTAuMDUgMTIgMTAuMDV6bTAtNy41NWMuMzY3IDAgLjY2Ny4yODEuNjY3LjYyNXMtLjMuNjI1LS42NjcuNjI1Yy0uMzY3IDAtLjY2Ny0uMjgxLS42NjctLjYyNXMuMy0uNjI1LjY2Ny0uNjI1ek00IDguMTI1Yy0uMzY3IDAtLjY2Ny0uMjgxLS42NjctLjYyNXMuMy0uNjI1LjY2Ny0uNjI1Yy4zNjcgMCAuNjY3LjI4MS42NjcuNjI1cy0uMy42MjUtLjY2Ny42MjV6bTggNC4zODdjLS4zNjcgMC0uNjY3LS4yOC0uNjY3LS42MjUgMC0uMzQzLjMtLjYyNS42NjctLjYyNS4zNjcgMCAuNjY3LjI4Mi42NjcuNjI1IDAgLjM0NC0uMy42MjUtLjY2Ny42MjV6IiBmaWxsLXJ1bGU9ImV2ZW5vZGQiLz48L3N2Zz4=');background-repeat:no-repeat;-webkit-background-size:contain;background-size:contain;}</style><style data-emotion="css hhaq4l" data-s="">.css-hhaq4l{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;margin:0.2rem;cursor:pointer;}.css-hhaq4l:before{display:inline-block;content:'';width:2.4rem;height:2.4rem;background-image:url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTExIDJjLTEuMTYgMC0yLjI3My41NC0zIDEuMzkzQTMuOTkyIDMuOTkyIDAgMDA1IDJhMy42MzEgMy42MzEgMCAwMC0zLjY2NyAzLjY2N2MwIDIuNTIgMi4yNjcgNC41NzMgNS43IDcuNjkzbC45NjcuODczLjk2Ny0uODhjMy40MzMtMy4xMTMgNS43LTUuMTY2IDUuNy03LjY4NkEzLjYzMSAzLjYzMSAwIDAwMTEgMnpNOC4wNjcgMTIuMzY3TDggMTIuNDMzbC0uMDY3LS4wNjZjLTMuMTczLTIuODc0LTUuMjY2LTQuNzc0LTUuMjY2LTYuNyAwLTEuMzM0IDEtMi4zMzQgMi4zMzMtMi4zMzQgMS4wMjcgMCAyLjAyNy42NiAyLjM4IDEuNTc0aDEuMjQ3QzguOTczIDMuOTkzIDkuOTczIDMuMzMzIDExIDMuMzMzYzEuMzMzIDAgMi4zMzMgMSAyLjMzMyAyLjMzNCAwIDEuOTI2LTIuMDkzIDMuODI2LTUuMjY2IDYuN3oiIGZpbGwtcnVsZT0iZXZlbm9kZCIvPjwvc3ZnPg==');background-repeat:no-repeat;-webkit-background-size:contain;background-size:contain;}</style><style data-emotion="css 1wbp5wz" data-s="">.css-1wbp5wz{font-size:1.2rem;font-weight:bold;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;margin:0.8rem 0 0.4rem;padding:0 2rem;color:#1a1a1a;cursor:pointer;}</style><style data-emotion="css 1c6fs9p" data-s="">.css-1c6fs9p{margin-right:0.2rem;}</style><style data-emotion="css 189aa3t" data-s="">.css-189aa3t{margin-right:0.1rem;}</style><style data-emotion="css 15gzbke" data-s="">.css-15gzbke{font-size:1.2rem;font-weight:normal;margin-right:0.5rem;height:1.4rem;}</style><style data-emotion="css fo8k40" data-s="">.css-fo8k40{display:inline-block;height:1.4rem;}.css-fo8k40:before{display:inline-block;content:'';width:1.2rem;height:1.2rem;background-image:url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTIiIGhlaWdodD0iMTIiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTMuMjQ1IDkuOTZsLjg4NS44NTQgNC45NS00Ljc4LTQuOTUtNC43NzktLjg4NS44NTVMNy4zMSA2LjAzNCAzLjI0NSA5Ljk2eiIgZmlsbD0iIzYxNjE2MSIgZmlsbC1ydWxlPSJldmVub2RkIi8+PC9zdmc+');background-repeat:no-repeat;-webkit-background-size:contain;background-size:contain;}</style><style data-emotion="css d4kyoo" data-s="">.css-d4kyoo{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;margin-top:0.5rem;padding:0 2rem;height:1.6rem;}</style><style data-emotion="css rub8sb" data-s="">.css-rub8sb{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;width:calc(100% - 7.6rem);}</style><style data-emotion="css 1jq3mm7" data-s="">.css-1jq3mm7{margin-right:0.4rem;}</style><style data-emotion="css 12kj640" data-s="">.css-12kj640{cursor:pointer;font-size:1.2rem;font-weight:normal;color:#0152cc;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}</style><style data-emotion="css 12hu69z" data-s="">.css-12hu69z{margin:0 2rem;border-bottom:0.1rem solid #f2f2f2;border-bottom:none;margin-bottom:0;}.css-12hu69z >*:first-of-type{border-top:0.1rem solid #f2f2f2;}.css-12hu69z >*:last-of-type{margin-bottom:1.2rem;}.css-12hu69z >div:nth-of-type(n + 2) .benefitBanner,.css-12hu69z >div:nth-of-type(n + 2) .imageBanner{margin-top:1.2rem;}</style><style data-emotion="css i7ka3p" data-s="">.css-i7ka3p{position:relative;display:-webkit-box;display:-webkit-flex;display:

In [16]:
#포항

In [17]:
name_list=soup.find_all("strong","PlaceListTitle_text__2511B normal")
name_text_list=[name.text for name in name_list]
name_text_list

['포항 비치드웨일풀빌라(미온수수영장)',
 '포항 스타스케이프풀빌라',
 '포항 고잉스테이풀빌라(22년9월신축)',
 '포항 꾸스풀빌라',
 '포항 에코팡팡(힐링)펜션',
 '포항 보경사온천파크펜션',
 '포항 어보브블루펜션(미온수무료)',
 '포항 슬로우오션풀빌라',
 '포항 더케이프펜션(석조노천탕,오션뷰)',
 '포항 다모아풀빌라',
 '포항 프레젠트풀빌라(신축,오션뷰)',
 '포항 빌라세비야펜션(22년1월신축)',
 '포항 네이처풀빌라펜션',
 '포항 피노키오풀빌라(미온수이벤트)',
 '포항 씨엔밤부펜션',
 '포항 소유가든풀빌라',
 '포항 연인바위펜션',
 '포항 씨엔스톤펜션',
 '포항 씨엔242펜션',
 '포항 씨클라우드펜션',
 '포항 베러키즈풀빌라',
 '포항 그레이스독채풀빌라펜션(21년8월 신축)',
 '포항 플레이비치풀빌라(19.7월신축)',
 '포항 디오션펜션',
 '포항 36.오도펜션',
 '포항 그랑모던풀빌라',
 '포항 연오랑187그리고바다풀빌라(신축)',
 '포항 유니의바다풀빌라',
 '포항 케렌시아풀빌라',
 '포항 아이세상키즈풀빌라',
 '포항 유니의바다카라반(호미곶점)',
 '포항 화이트7풀빌라',
 '포항 파인웨이브스파펜션(오션뷰)',
 '포항 포에스카라반파크',
 '포항 더헤이븐리조트펜션(오션뷰)',
 '포항 피유키즈풀빌라',
 '포항 코지스위트펜션',
 '포항 더원키즈풀빌라',
 '포항 Sea&Bamboo펜션',
 '포항 테스226풀빌라',
 '포항 오도힐풀빌라(22년 올리모델링)',
 '포항 해송펜션 (독채야외돔풀빌라)']

In [18]:
len(name_text_list)

42

In [19]:
rename_list=[]
exp_list=[]
for i in range(42):
    rename_list.append(name_text_list[i].split('(')[0])
    if len(rename_list[i])==len(name_text_list[i]):
        exp_list.append('없음')
    else:
        exp_list.append(name_text_list[i].split('(')[1])

In [20]:
reexp_list=[]
for i in range(42):
    reexp_list.append(exp_list[i].split(')')[0])
reexp_list

['미온수수영장',
 '없음',
 '22년9월신축',
 '없음',
 '힐링',
 '없음',
 '미온수무료',
 '없음',
 '석조노천탕,오션뷰',
 '없음',
 '신축,오션뷰',
 '22년1월신축',
 '없음',
 '미온수이벤트',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '21년8월 신축',
 '19.7월신축',
 '없음',
 '없음',
 '없음',
 '신축',
 '없음',
 '없음',
 '없음',
 '호미곶점',
 '없음',
 '오션뷰',
 '없음',
 '오션뷰',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '22년 올리모델링',
 '독채야외돔풀빌라']

In [21]:
point_list=soup.find_all("span","PlaceListScore_rating__3Glxf")
point_text_list=[float(point.text) for point in point_list]
point_text_list

[4.3,
 4.8,
 5.0,
 4.5,
 4.2,
 4.5,
 4.5,
 4.7,
 4.9,
 4.9,
 4.4,
 4.9,
 4.6,
 4.9,
 4.7,
 3.8,
 4.6,
 4.6,
 3.9,
 4.7,
 2.7,
 5.0,
 4.8,
 4.7,
 4.8,
 4.6,
 4.9,
 4.9,
 4.9,
 5.0,
 4.9,
 4.8,
 4.6,
 4.7,
 5.0,
 4.3,
 4.2,
 4.5,
 4.8,
 4.1,
 4.6,
 4.7,
 4.8,
 4.8,
 4.4,
 4.9,
 4.8,
 4.3,
 4.6,
 4.6,
 4.1,
 2.9,
 5.0,
 3.3,
 4.9,
 4.7,
 5.0,
 4.9,
 5.0,
 4.8,
 3.7,
 4.6]

In [22]:
len(point_text_list)

62

In [23]:
point_text_list=point_text_list[:42]
len(point_text_list)

42

In [24]:
hotel_df=pd.DataFrame({'이름':rename_list})
hotel_df['평균평점']=point_text_list
hotel_df['설명']=reexp_list
hotel_df

                   이름  평균평점         설명
0         포항 비치드웨일풀빌라   4.3     미온수수영장
1        포항 스타스케이프풀빌라   4.8         없음
2         포항 고잉스테이풀빌라   5.0    22년9월신축
3            포항 꾸스풀빌라   4.5         없음
4             포항 에코팡팡   4.2         힐링
5        포항 보경사온천파크펜션   4.5         없음
6          포항 어보브블루펜션   4.5      미온수무료
7         포항 슬로우오션풀빌라   4.7         없음
8           포항 더케이프펜션   4.9  석조노천탕,오션뷰
9           포항 다모아풀빌라   4.9         없음
10         포항 프레젠트풀빌라   4.4     신축,오션뷰
11         포항 빌라세비야펜션   4.9    22년1월신축
12        포항 네이처풀빌라펜션   4.6         없음
13         포항 피노키오풀빌라   4.9     미온수이벤트
14          포항 씨엔밤부펜션   4.7         없음
15         포항 소유가든풀빌라   3.8         없음
16          포항 연인바위펜션   4.6         없음
17          포항 씨엔스톤펜션   4.6         없음
18         포항 씨엔242펜션   3.9         없음
19         포항 씨클라우드펜션   4.7         없음
20         포항 베러키즈풀빌라   2.7         없음
21     포항 그레이스독채풀빌라펜션   5.0   21년8월 신축
22        포항 플레이비치풀빌라   4.8    19.7월신축
23           포항 디오션펜션   4.7         없음
24         포항 36.오도펜션   4.8         없음
25         포항 그랑모던풀빌라   4.6         없음
26  포항 연오랑187그리고바다풀빌라   4.9         신축
27        포항 유니의바다풀빌라   4.9         없음
28         포항 케렌시아풀빌라   4.9         없음
29       포항 아이세상키즈풀빌라   5.0         없음
30        포항 유니의바다카라반   4.9       호미곶점
31         포항 화이트7풀빌라   4.8         없음
32       포항 파인웨이브스파펜션   4.6        오션뷰
33        포항 포에스카라반파크   4.7         없음
34       포항 더헤이븐리조트펜션   5.0        오션뷰
35         포항 피유키즈풀빌라   4.3         없음
36         포항 코지스위트펜션   4.2         없음
37         포항 더원키즈풀빌라   4.5         없음
38    포항 Sea&Bamboo펜션   4.8         없음
39        포항 테스226풀빌라   4.1         없음
40          포항 오도힐풀빌라   4.6  22년 올리모델링
41           포항 해송펜션    4.7   독채야외돔풀빌라

In [25]:
address=soup.find("span","PlaceListTitle_normal__318s-")
hotel_df['주소']=address.text
hotel_df

                   이름  평균평점         설명  주소
0         포항 비치드웨일풀빌라   4.3     미온수수영장  포항
1        포항 스타스케이프풀빌라   4.8         없음  포항
2         포항 고잉스테이풀빌라   5.0    22년9월신축  포항
3            포항 꾸스풀빌라   4.5         없음  포항
4             포항 에코팡팡   4.2         힐링  포항
5        포항 보경사온천파크펜션   4.5         없음  포항
6          포항 어보브블루펜션   4.5      미온수무료  포항
7         포항 슬로우오션풀빌라   4.7         없음  포항
8           포항 더케이프펜션   4.9  석조노천탕,오션뷰  포항
9           포항 다모아풀빌라   4.9         없음  포항
10         포항 프레젠트풀빌라   4.4     신축,오션뷰  포항
11         포항 빌라세비야펜션   4.9    22년1월신축  포항
12        포항 네이처풀빌라펜션   4.6         없음  포항
13         포항 피노키오풀빌라   4.9     미온수이벤트  포항
14          포항 씨엔밤부펜션   4.7         없음  포항
15         포항 소유가든풀빌라   3.8         없음  포항
16          포항 연인바위펜션   4.6         없음  포항
17          포항 씨엔스톤펜션   4.6         없음  포항
18         포항 씨엔242펜션   3.9         없음  포항
19         포항 씨클라우드펜션   4.7         없음  포항
20         포항 베러키즈풀빌라   2.7         없음  포항
21     포항 그레이스독채풀빌라펜션   5.0   21년8월 신축  포항
22        포항 플레이비치풀빌라   4.8    19.7월신축  포항
23           포항 디오션펜션   4.7         없음  포항
24         포항 36.오도펜션   4.8         없음  포항
25         포항 그랑모던풀빌라   4.6         없음  포항
26  포항 연오랑187그리고바다풀빌라   4.9         신축  포항
27        포항 유니의바다풀빌라   4.9         없음  포항
28         포항 케렌시아풀빌라   4.9         없음  포항
29       포항 아이세상키즈풀빌라   5.0         없음  포항
30        포항 유니의바다카라반   4.9       호미곶점  포항
31         포항 화이트7풀빌라   4.8         없음  포항
32       포항 파인웨이브스파펜션   4.6        오션뷰  포항
33        포항 포에스카라반파크   4.7         없음  포항
34       포항 더헤이븐리조트펜션   5.0        오션뷰  포항
35         포항 피유키즈풀빌라   4.3         없음  포항
36         포항 코지스위트펜션   4.2         없음  포항
37         포항 더원키즈풀빌라   4.5         없음  포항
38    포항 Sea&Bamboo펜션   4.8         없음  포항
39        포항 테스226풀빌라   4.1         없음  포항
40          포항 오도힐풀빌라   4.6  22년 올리모델링  포항
41           포항 해송펜션    4.7   독채야외돔풀빌라  포항

In [103]:
#driver.find_element('xpath','//*[@id="__next"]/div[2]/section[2]/div[1]/div/div[1]/a/div[2]/div[1]/div[1]/strong').click()

In [29]:
#driver.find_element('xpath','//*[@id="__next"]/div/div/main/article/div[2]/div/div[1]/div/button[2]/a').click()

In [30]:
#driver.find_element('xpath','//*[@id="__next"]/div/div/main/article/div[1]/div[1]/div[5]/div/span').click()

In [31]:
#from selenium.webdriver.common.by import By
#address=driver.find_element(By.CSS_SELECTOR,"#_MODAL_DIM_ > div > div > div > main > div > div.css-rdhsb9 > div.css-1yjxi0j > div:nth-child(1)")
#address.text

'경상북도 포항시 남구 호미곶면 구만길 178'

In [35]:
driver.find_element('xpath','//*[@id="__next"]/div/div/header/div/div[1]/div[1]/img').click()

In [96]:
#주소
from selenium.webdriver.common.by import By
address_list=[]
for i in range(42):
    if i%4==1:
        c=2
    elif i%4==2:
        c=3
    elif i%4==3:
        c=4
    else:
        c=1

    a='//*[@id="__next"]/div[2]/section[2]/div[1]/div/div['
    b=']/a/div[2]/div[1]/div[1]/strong'
    
    try:
        driver.find_element('xpath',a+str(c)+b).click()
        driver.find_element('xpath','//*[@id="__next"]/div/div/main/article/div[2]/div/div[1]/div/button[2]/a').click()
        address=driver.find_element(By.CSS_SELECTOR,"#_MODAL_DIM_ > div > div > div > main > div > div.css-rdhsb9 > div.css-1yjxi0j > div:nth-child(1)")
        address_list[i]=address.text
        print(address_list[i])
        driver.find_element('xpath','//*[@id="_MODAL_DIM_"]/div/div/div/header/div/div[1]/img').click()
        document.querySelector("#__next > div.StyleComponent_container__1jS9A.list_listContainer__2kL99.list_bottomPadding__xvWzu > section.PlaceListBody_placeListBodyContainer__1u70R > div:nth-child(1) > div > div:nth-child(3) > a > div.PlaceListItemBanner_image__1-YJA > div.PlaceListImage_container__t-mGF > div.PlaceListImage_imageBig__3YLxw")  
    except:
         print("except")
        
address_list

except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except
except

[]

In [102]:
hotel_df

                   이름  평균평점         설명  주소
0         포항 비치드웨일풀빌라   4.3     미온수수영장  포항
1        포항 스타스케이프풀빌라   4.8         없음  포항
2         포항 고잉스테이풀빌라   5.0    22년9월신축  포항
3            포항 꾸스풀빌라   4.5         없음  포항
4             포항 에코팡팡   4.2         힐링  포항
5        포항 보경사온천파크펜션   4.5         없음  포항
6          포항 어보브블루펜션   4.5      미온수무료  포항
7         포항 슬로우오션풀빌라   4.7         없음  포항
8           포항 더케이프펜션   4.9  석조노천탕,오션뷰  포항
9           포항 다모아풀빌라   4.9         없음  포항
10         포항 프레젠트풀빌라   4.4     신축,오션뷰  포항
11         포항 빌라세비야펜션   4.9    22년1월신축  포항
12        포항 네이처풀빌라펜션   4.6         없음  포항
13         포항 피노키오풀빌라   4.9     미온수이벤트  포항
14          포항 씨엔밤부펜션   4.7         없음  포항
15         포항 소유가든풀빌라   3.8         없음  포항
16          포항 연인바위펜션   4.6         없음  포항
17          포항 씨엔스톤펜션   4.6         없음  포항
18         포항 씨엔242펜션   3.9         없음  포항
19         포항 씨클라우드펜션   4.7         없음  포항
20         포항 베러키즈풀빌라   2.7         없음  포항
21     포항 그레이스독채풀빌라펜션   5.0   21년8월 신축  포항
22        포항 플레이비치풀빌라   4.8    19.7월신축  포항
23           포항 디오션펜션   4.7         없음  포항
24         포항 36.오도펜션   4.8         없음  포항
25         포항 그랑모던풀빌라   4.6         없음  포항
26  포항 연오랑187그리고바다풀빌라   4.9         신축  포항
27        포항 유니의바다풀빌라   4.9         없음  포항
28         포항 케렌시아풀빌라   4.9         없음  포항
29       포항 아이세상키즈풀빌라   5.0         없음  포항
30        포항 유니의바다카라반   4.9       호미곶점  포항
31         포항 화이트7풀빌라   4.8         없음  포항
32       포항 파인웨이브스파펜션   4.6        오션뷰  포항
33        포항 포에스카라반파크   4.7         없음  포항
34       포항 더헤이븐리조트펜션   5.0        오션뷰  포항
35         포항 피유키즈풀빌라   4.3         없음  포항
36         포항 코지스위트펜션   4.2         없음  포항
37         포항 더원키즈풀빌라   4.5         없음  포항
38    포항 Sea&Bamboo펜션   4.8         없음  포항
39        포항 테스226풀빌라   4.1         없음  포항
40          포항 오도힐풀빌라   4.6  22년 올리모델링  포항
41           포항 해송펜션    4.7   독채야외돔풀빌라  포항

In [104]:
data_path='/Users/kimminkyoung/Desktop/AI데이터입문/'
hotel_df.to_excel(data_path+'hotel.xlsx')